// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Ha5qoeKQuhNhwfWtmIgxSewuWpclJXE',
    appId: '1:475205871903:web:0ac8ffdfe91b597c7ce82a',
    messagingSenderId: '475205871903',
    projectId: 'mission-app-b29ed',
    authDomain: 'mission-app-b29ed.firebaseapp.com',
    storageBucket: 'mission-app-b29ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRan1zel-CjArvR2zuhCHxNvEpbaKN73c',
    appId: '1:475205871903:android:8fba92343376dbc67ce82a',
    messagingSenderId: '475205871903',
    projectId: 'mission-app-b29ed',
    storageBucket: 'mission-app-b29ed.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Ha5qoeKQuhNhwfWtmIgxSewuWpclJXE',
    appId: '1:475205871903:web:83046b721fabf94a7ce82a',
    messagingSenderId: '475205871903',
    projectId: 'mission-app-b29ed',
    authDomain: 'mission-app-b29ed.firebaseapp.com',
    storageBucket: 'mission-app-b29ed.firebasestorage.app',
  );

}